variables:
  SYS_INFO_URL: "https://www.mytuxedo.de/remote.php/webdav/systeminfo-sh/systeminfos.sh"

stages:
  - deploy

upload_mytuxedo:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - systeminfos.sh
  script:
    - curl -T ./systeminfos.sh --user ${K8S_SECRET_WEBDAV_USER}:${K8S_SECRET_WEBDAV_PASSWORD} ${SYS_INFO_URL}